### ISSUE TITLE
Problem with 'textsize'

### ISSUE THREAD

**Issue by PCov3r** [adafruit/TFTLCD-Library#37]
Hello, 
first of all, thank you for making such a good library. 

I tried using the example tftbmp on my arduino mega to display bmp on my screen 
(the screen model : https://www.amazon.fr/Kuman-Tactile-Arduino-Module-Fonction/dp/B075CXXL1M/ref=sr_1_1?ie=UTF8&qid=1528549257&sr=8-1&keywords=tft+arduino+uno )

Here's the problem. When I try to upload the code, I get the following error : 

TFTLCD-Library-master\Adafruit_TFTLCD.cpp:115:3: error: 'textsize' was not declared in this scope

   textsize  = 1;

How may I solve it ?

**Comment by JAICHANGPARK** [comment]
Same problem

**Comment by darkpanda08** [comment]
Use Adafruit GFX library version 1.5.3 The newer versions of this library have broken everything.

**Comment by JAICHANGPARK** [comment]
@darkpanda08  Thanks

**Comment by PCov3r** [comment]
Thanks !

**Comment by SamuelDave** [comment]
issue still persists with mine, please help
