### ISSUE TITLE
warning: backslash and newline separated by space

### ISSUE THREAD

**Issue by amayem** [adafruit/TFTLCD-Library#40]
- Arduino board:  Mega

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

The following code
`#include <Adafruit_GFX.h>    // Core graphics library
#include <Adafruit_TFTLCD.h> // Hardware-specific library

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}`

Gives the following error
`Arduino\libraries\Adafruit_TFTLCD_Library\pin_magic.h:282:33: warning: backslash and newline separated by space

   #define read8inline(result) { \    

                                 ^`

**Comment by ladyada** [comment]
should be fixed by 
https://github.com/adafruit/TFTLCD-Library/commit/5b2bead71bacf082fc286e39c68175a9ed0a2c3b
