### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by arm358** [adafruit/TFTLCD-Library#51]
I have a program running on a Mega in 8-bit mode writing to the Adafruit 3.5" TFT display with touchscreen.

In the examples for this screen it mentions that the D0-D7 pins are hardcoded to certain pins on the uno and the mega. 

Does this library support other boards such as ESP32? I assume all I need to do is change the configuration for the D0-D7 pins. Can you confirm this is the case?

**Comment by ladyada** [comment]
nope compltely unsupported. you'll need another library for 8bit support on esp32!
