### ISSUE TITLE
Can you please add the ILI9486?

### ISSUE THREAD

**Issue by ghost** [adafruit/TFTLCD-Library#56]
I want to do a calculator on my 3.5" TFT Display but this library works with the touchscreen library without failing. Can you please add a driver for that chip?

**Comment by ladyada** [comment]
hiya - which adafruit product did you purchase?

**Comment by ghost** [comment]
The 3.5" TFT display

**Comment by ladyada** [comment]
where did you buy it? the exact URL

**Comment by ghost** [comment]
I got it from amazon

**Comment by ladyada** [comment]
great - please contact them to get support added!

**Comment by ghost** [comment]
Is there a way to initialize the with and hight manually?

**Comment by ladyada** [comment]
there is not!
